# Generated by Django 5.2.3 on 2025-07-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Staff_id',
        ),
    ]
