# Generated by Django 5.2.4 on 2025-07-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_app', '0002_remove_student_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='Staff_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Address_Staff',
            fields=[
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('subcounty', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Class_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Address_Student',
            fields=[
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('subcounty', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Class_app.student')),
            ],
        ),
    ]
