# Generated by Django 5.2.4 on 2025-07-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_app', '0004_alter_staff_staff_id_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_staff',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Class_app.staff'),
        ),
        migrations.AlterField(
            model_name='address_student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Class_app.student'),
        ),
    ]
